### ISSUE TITLE
Bug when converting into Latex

### ISSUE THREAD

**Issue by nhan000** [hkgnp/darwis-mathlive-plugin#2] opened 2022-02-25 02:22 UTC
Please see the screen recording

https://user-images.githubusercontent.com/85216095/155641466-5832a683-2d2a-4c0e-853e-e2ce729a0208.mp4

**Comment by benjypng** [comment] 2022-02-25 11:22
Do you know where is this `\differentialID`coming from?

**Comment by nhan000** [comment] 2022-02-25 20:29
I don't know. I just typed the equation in and have no idea why `\differentialID` popped up. Could you reproduce the bug?

**Comment by benjypng** [comment] 2022-02-26 03:33
Unfortunately I am not able to. Is this the only bug? 

If you type "t t" into the mathlive box, does your theme change as well?

**Comment by nhan000** [comment] 2022-02-26 07:02
"t t" causes changing between dark and light theme

**Comment by benjypng** [comment] 2022-02-28 08:34
That's interesting. Do you mind sharing the whole list of plugins that you currently have installed?

**Comment by nhan000** [comment] 2022-02-28 09:35
This is all that I'm using
![image](https://user-images.githubusercontent.com/85216095/155959533-9031f248-9c49-4b54-8d8d-4fc0bf33e481.png)

**Comment by benjypng** [comment] 2022-03-02 14:19
Unfortunately, I am not able to reproduce the bug! Will continue to keep it open as at least one other person is experiencing this.

Strange indeed! 🤔

**Comment by nhan000** [comment] 2022-04-05 03:29
As I started using the plugin more it's bugging me quite a bit.

The bug seems to be that it registers the keystrokes as if I'm _not_ in editing mode. For example:

If I press `c` it put a letter "c" in the Math Editor but will also bring up the Git commit pop up.
`t t` will switch light/dark theme
`t i` will bring up the changing theme pop up.
and so on with `t p`, `g j`, etc.

(I think I and another user who had this problem before all use Windows, and I know you use Mac so you may not see this bug ha ha)

**Comment by nhan000** [comment] 2022-04-05 03:29
As I started using the plugin more it's bugging me quite a bit.

The bug seems to be that it registers the keystrokes as if I'm _not_ in editing mode. For example:

If I press `c` it put a letter "c" in the Math Editor but will also bring up the Git commit pop up.
`t t` will switch light/dark theme
`t i` will bring up the changing theme pop up.
and so on with `t p`, `g j`, etc.

**Comment by benjypng** [comment] 2022-04-08 07:46
@nhan000 Hey thanks for reporting this. Yes, Yuval from the Discord experienced the exact same issue as well. Unfortunately, even the Logseq devs are not able to reproduce this bug. I've had other users on Windows (as well as using my Windows VM) and still not able to do so!

As mentioned above, will keep this open just in case a solution pops up.

**Comment by nhan000** [comment] 2023-04-16 18:48
Just found out that the bug is from the source https://cortexjs.io/mathlive/demo/. Input the same equation $$\frac{dN}{dt}$$ and got the same bug. The weird thing is IIRC, the bug wasn't there when I used it a year ago (but again it was year ago so my memory may not be accurate). I want to file a bug report with them but I don't know where to do that. I'm on Logseq 0.9.2 on Windows 11.

Good news is the bug of pressing `t t` and `t i` or any other Logseq shortcuts no longer trigger Logseq's commands.

Though the input box now shrinks to a very small one 
![image](https://user-images.githubusercontent.com/85216095/232335045-42f1808c-9f37-4ec9-9d1b-c7ea9abba3dc.png)

**Comment by benjypng** [comment] 2023-04-17 23:06
> Just found out that the bug is from the source https://cortexjs.io/mathlive/demo/. Input the same equation dNdt=RA and got the same bug. The weird thing is IIRC, the bug wasn't there when I used it a year ago (but again it was year ago so my memory may not be accurate). I want to file a bug report with them but I don't know where to do that. I'm on Logseq 0.9.2 on Windows 11.
> 
> Good news is the bug of pressing `t t` and `t i` or any other Logseq shortcuts no longer trigger Logseq's commands.
> 
> Though the input box now shrinks to a very small one ![image](https://user-images.githubusercontent.com/85216095/232335045-42f1808c-9f37-4ec9-9d1b-c7ea9abba3dc.png)

Apologies, fixed in the latest version.

**Closed as completed by benjypng** 2023-04-17 23:06 UTC
